BOARD_LIST = [
    "Go",
    "Old Kent Road",
    "Community Chest",
    "Whitechapel Road",
    "Income Tax",
    "King's Cross Station",
    "The Angel Islington",
    "Chance",
    "Euston Road",
    "Pentonville Road",
    "Jail",
    "Pall Mall",
    "Electric Company",
    "Whitehall",
    "Northumberland Avenue",
    "Marylebone Station",
    "Bow Street",
    "Community Chest",
    "Marlborough Street",
    "Vine Street",
    "Free Parking",
    "Strand",
    "Chance",
    "Fleet Street",
    "Trafalgar Square",
    "Fenchurch St Station",
    "Leicester Square",
    "Coventry Street",
    "Water Works",
    "Piccadilly",
    "Go to Jail",
    "Regent Street",
    "Oxford Street",
    "Community Chest",
    "Bond Street",
    "Liverpool St Station",
    "Chance",
    "Park Lane",
    "Super Tax",
    "Mayfair",
]

NAME_TO_INDEX = {name: index for index, name in enumerate(BOARD_LIST)}

COLOUR_MAP = {
    1: "Brown",
    3: "Brown",
    6: "Light Blue",
    8: "Light Blue",
    9: "Light Blue",
    11: "Pink",
    13: "Pink",
    14: "Pink",
    16: "Orange",
    18: "Orange",
    19: "Orange",
    21: "Red",
    23: "Red",
    24: "Red",
    26: "Yellow",
    27: "Yellow",
    29: "Yellow",
    31: "Green",
    32: "Green",
    34: "Green",
    37: "Dark Blue",
    39: "Dark Blue",
}

